### ISSUE TITLE
should this work on OSX?

### ISSUE THREAD

**Issue by rabarar** [0xfe/mobot#1]
trying to run the bots on OSX - I see the handler getting called, but the ` Ok(chat::Action::ReplyText("Hello world!".into()))` doesn't make it's way back to the chat

**Comment by 0xfe** [comment]
Hey Rob! Sorry, I broke it to support markdown replies. It's fixed now :-)

(BTW, easier to use the crate from cargo, since it's more stable.)

**Comment by rabarar** [comment]
Zero worries!!! Btw, I jumped into rust a month ago. Absolutely love it!!I pulled the repo more to read the code than anything else…Might make a docker container for it tomorrow…Nicely done Mo!On May 5, 2023, at 6:30 PM, Mohit Cheppudira ***@***.***> wrote:﻿
Hey Rob! Sorry, I broke it to support markdown replies. It's fixed now :-)
(BTW, easier to use the crate from cargo, since it's more stable.)
